<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>
		</title>
		<style type="text/css">
			.csAD577193{text-align:left;text-indent:0pt;margin:24pt 0pt 0pt 0pt;page-break-after:avoid;page-break-inside:avoid}
			.csECDA2D3{color:#4F81BD;background-color:transparent;font-family:Microsoft YaHei UI;font-size:16pt;font-weight:bold;font-style:normal;}
			.csDE05BCC{color:#4F81BD;background-color:transparent;font-family:Calibri;font-size:16pt;font-weight:bold;font-style:normal;}
			.cs868C439D{text-align:left;text-indent:0pt;margin:10pt 0pt 0pt 0pt;page-break-after:avoid;page-break-inside:avoid}
			.cs83F14626{color:#4F81BD;background-color:transparent;font-family:Microsoft YaHei UI;font-size:14pt;font-weight:bold;font-style:normal;}
			.cs40DD2BC9{text-align:left;text-indent:0pt;margin:9pt 0pt 9pt 0pt}
			.cs8926E06{color:#000000;background-color:transparent;font-family:Calibri;font-size:12pt;font-weight:normal;font-style:normal;}
			.cs9C1B1871{color:#000000;background-color:transparent;font-family:Microsoft YaHei UI;font-size:12pt;font-weight:normal;font-style:normal;}
			.cs9FB05234{color:#000000;background-color:transparent;font-family:Consolas;font-size:11pt;font-weight:normal;font-style:normal;}
			.cs63189908{text-align:left;margin:0pt 0pt 10pt 0pt;list-style-type:decimal;color:#000000;background-color:transparent;font-family:Calibri;font-size:12pt;font-weight:normal;font-style:normal}
			.cs3A447A38{text-align:left;text-indent:0pt;margin:0pt 0pt 10pt 0pt}
		</style>
	</head>
	<body>
		<h1 class="csAD577193">
			<a name="cve-2017-12794django-debug-page-xss漏洞"><span class="csECDA2D3">（</span><span class="csDE05BCC">CVE-2017-12794</span><span class="csECDA2D3">）</span><span class="csDE05BCC">Django debug page XSS</span><span class="csECDA2D3">漏洞</span></a></h1>
		<h2 class="cs868C439D">
			<a name="一漏洞简介"><span class="cs83F14626">一、漏洞简介</span></a></h2>
		<p class="cs40DD2BC9"><span class="cs8926E06">Django </span><span class="cs9C1B1871">发布了新版本</span><span class="cs8926E06">1.11.5</span><span class="cs9C1B1871">，修复了</span><span class="cs8926E06">500</span><span class="cs9C1B1871">页面中可能存在的一个</span><span class="cs8926E06"> XSS </span><span class="cs9C1B1871">漏洞</span></p><h2 class="cs868C439D">
			<a name="二漏洞影响"><span class="cs83F14626">二、漏洞影响</span></a></h2>
		<p class="cs40DD2BC9"><span class="cs8926E06">Django &lt; 1.11.5</span></p><h2 class="cs868C439D">
			<a name="三复现过程"><span class="cs83F14626">三、复现过程</span></a></h2>
		<p class="cs40DD2BC9"><span class="cs9C1B1871">经过我的测试，我发现在使用</span><span class="cs8926E06">Postgres</span><span class="cs9C1B1871">数据库并触发异常的时候，</span><span class="cs8926E06">psycopg2</span><span class="cs9C1B1871">会将字段名和字段值全部抛出。那么，如果字段值中包含我们可控的字符串，又由于</span><span class="cs8926E06">0x02</span><span class="cs9C1B1871">中说到的，这个字符串其实就会被设置成</span><span class="cs9FB05234">__cause__</span><span class="cs9C1B1871">，最后被显示在页面中。</span></p><p class="cs40DD2BC9"><span class="cs9C1B1871">所以我们假设有如下场景：</span></p><ol start="1" style="margin-top:0;margin-bottom:0;">
			<li class="cs63189908"><span class="cs9C1B1871">用户注册页面，未检查用户名</span></li><li class="cs63189908"><span class="cs9C1B1871">注册一个用户名为</span><span class="cs9FB05234">alert(1)</span><span class="cs9C1B1871">的用户</span></li><li class="cs63189908"><span class="cs9C1B1871">再次注册一个用户名为</span><span class="cs9FB05234">alert(1)</span><span class="cs9C1B1871">的用户</span></li><li class="cs63189908"><span class="cs9C1B1871">触发</span><span class="cs8926E06">duplicate key</span><span class="cs9C1B1871">异常，导致</span><span class="cs8926E06">XSS</span><span class="cs9C1B1871">漏洞</span></li></ol>
		<p class="cs40DD2BC9"><span class="cs9C1B1871">访问</span><span class="cs9FB05234">http://www.0-sec.org:8000/create_user/?username=alert(1)</span><span class="cs9C1B1871">创建一个用户，成功；再次访问</span><span class="cs9FB05234">http://www.0-sec.org:8000/create_user/?username=alert(1)</span><span class="cs9C1B1871">，触发异常：</span></p><p class="cs40DD2BC9"><span><img src="Web安全/Django/%ef%bc%88CVE-2017-12794%ef%bc%89Django%20debug%20page%20XSS%e6%bc%8f%e6%b4%9e_files/image0.png" width="560" height="452" alt="" style="border-width:0px;" /></span></p><p class="cs40DD2BC9"><span class="cs9C1B1871">可见，</span><span class="cs8926E06">Postgres</span><span class="cs9C1B1871">抛出的异常为</span></p><p class="cs3A447A38"><span class="cs9FB05234">duplicate key value violates unique constraint &quot;xss_user_username_key&quot;</span><span class="cs8926E06"><br/></span><span class="cs9FB05234">DETAIL: &nbsp;Key (username)=(&lt;script&gt;alert(1)&lt;/script&gt;) already exists.</span></p><p class="cs40DD2BC9"><span class="cs9C1B1871">这个异常被拼接进</span><span class="cs9FB05234">The above exception ({{ frame.exc_cause }}) was the direct cause of the following exception</span><span class="cs9C1B1871">，最后触发</span><span class="cs8926E06">XSS</span><span class="cs9C1B1871">。</span></p></body>
</html>
